import { test, expect } from '@playwright/test'

const organisation = '00000000-0000-4000-8000-000000000001'
test.use({ trace: 'off' })

test('findings triage renders evidence and keeps repair unavailable', async ({ page }) => {
  await page.goto('/auth/login')
  await expect(page).toHaveURL(/\/org\/[^/]+\/overview/)
  await page.route(`**/api/v1/orgs/${organisation}/findings**`, route => route.fulfill({ json: { items: [{ id: 'finding-1', org_id: organisation, repository_id: 'repo-1', source: 'advisory', source_id: 'CVE-TEST', category: 'dependency', severity: 'high', title: 'Upgrade dependency', evidence: { provenance: 'gitea', connection_id: 'connection-1', connection_version: 1, config_version: 1, head_sha: 'head123', target_sha: 'base123', target_branch: 'main', checks: [{ id: 'check-1', name: 'CI', publisher_id: 'ci', head_sha: 'head123', status: 'completed', conclusion: 'passed', url: 'https://ci.test/check/1' }], dependencies: [{ ecosystem: 'go', manifest: 'go.mod', name: 'example/module', from: '1.0.0', to: '1.1.0' }], ownership: 'bot-owned', bot: 'renovate', reference_url: 'https://advisory.test/CVE-TEST', complete: true, blockers: ['repair unavailable'], merge_blockers: ['checks pending'] }, fingerprint: 'fingerprint', evidence_digest: 'digest', state: 'open', reason: 'Needs review', version: 1, first_seen: new Date().toISOString(), last_seen: new Date().toISOString() }], complete: true } }))
  await page.route(`**/api/v1/orgs/${organisation}/findings/finding-1`, route => route.fulfill({ json: { id: 'finding-1', org_id: organisation, repository_id: 'repo-1', source: 'advisory', source_id: 'CVE-TEST', category: 'dependency', severity: 'high', title: 'Upgrade dependency', evidence: { provenance: 'gitea', connection_id: 'connection-1', connection_version: 1, config_version: 1, head_sha: 'head123', target_sha: 'base123', target_branch: 'main', checks: [{ id: 'check-1', name: 'CI', publisher_id: 'ci', head_sha: 'head123', status: 'completed', conclusion: 'passed', url: 'https://ci.test/check/1' }], dependencies: [{ ecosystem: 'go', manifest: 'go.mod', name: 'example/module', from: '1.0.0', to: '1.1.0' }], ownership: 'bot-owned', bot: 'renovate', reference_url: 'https://advisory.test/CVE-TEST', complete: true, blockers: ['repair unavailable'], merge_blockers: ['checks pending'] }, fingerprint: 'fingerprint', evidence_digest: 'digest', state: 'open', reason: 'Needs review', version: 1, first_seen: new Date().toISOString(), last_seen: new Date().toISOString() } }))
  await page.goto(`/org/${organisation}/findings?finding=finding-1`)
  await expect(page.getByRole('button', { name: 'Upgrade dependency' })).toBeVisible()
  const details = page.getByRole('region', { name: 'Upgrade dependency' })
  await expect(page.getByRole('button', { name: 'Close finding details' })).toBeFocused()
  await page.getByRole('button', { name: 'Close finding details' }).click()
  await expect(page.locator('.split-list')).toBeFocused()
  await page.getByRole('button', { name: 'Upgrade dependency' }).click()
  await expect(page.getByRole('button', { name: 'Close finding details' })).toBeFocused()
  await expect(details).toContainText('head123')
  await details.getByRole('tab', { name: 'Evidence' }).click()
  await expect(details).toContainText('example/module 1.0.0 → 1.1.0')
  await expect(details.getByRole('link', { name: 'source' })).toHaveCount(1)
  await details.getByRole('tab', { name: 'Repair' }).click()
  await expect(page.getByRole('button', { name: 'Generate preview' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Dismiss', exact: true })).toBeDisabled()
  await expect(page).toHaveURL(/finding=finding-1/)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('region', { name: 'Upgrade dependency' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upgrade dependency' })).toBeFocused()
  await page.getByRole('button', { name: 'Upgrade dependency' }).click()
  await page.goBack()
  await expect(page.getByRole('region', { name: 'Upgrade dependency' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Severity', exact: true }).selectOption('high')
  await expect(page).toHaveURL(/finding_severity=high/)
  await page.goBack()
  await expect(page.getByRole('combobox', { name: 'Severity', exact: true })).toHaveValue('')
})

test('triages a real imported repository finding through versioned actions', async ({ page }) => {
  test.skip(process.env.REFORGE_LIVE_GITEA_TEST !== '1', 'requires persisted imported repository fixture')
  test.setTimeout(90_000)
  await page.goto('/auth/login')
  await expect(page).toHaveURL(/\/org\/[^/]+\/overview/)
  const repositories = await page.request.get(`/api/v1/orgs/${organisation}/repositories?limit=1`)
  expect(repositories.ok()).toBe(true)
  const repository = (await repositories.json() as { items: Array<{ id: string; name: string }> }).items[0]
  expect(repository?.id).toBeTruthy()
  const title = `Browser advisory ${Date.now()}`
  await page.goto(`/org/${organisation}/findings`)
  await page.getByRole('button', { name: 'Import advisory' }).click()
  const importDialog = page.getByRole('dialog', { name: 'Import advisory' })
  await importDialog.getByLabel('advisory id').fill(`CVE-BROWSER-${Date.now()}`)
  await importDialog.getByLabel('title').fill(title)
  await importDialog.getByLabel('severity').selectOption('high')
  await importDialog.getByLabel('reference url').fill('https://example.test/advisory')
  await importDialog.getByLabel('path').fill('go.mod')
  await importDialog.getByLabel('package').fill('example.test/module')
  await importDialog.getByLabel('ecosystem').fill('go')
  await importDialog.getByLabel('affected range').fill('< 1.2.3')
  await importDialog.getByLabel('commit sha').fill('0123456789abcdef0123456789abcdef01234567')
  await importDialog.getByLabel('Repository').selectOption(repository.id)
  await importDialog.getByRole('button', { name: 'Import advisory' }).click()
  const findingButton = page.getByRole('button', { name: title })
  await expect(findingButton).toBeVisible({ timeout: 20_000 })
  await findingButton.click()
  const details = page.getByRole('region', { name: title })
  const findingAPI = () => page.request.get(`/api/v1/orgs/${organisation}/findings?limit=50&q=${encodeURIComponent(title)}`).then(response => response.json() as Promise<{ items: Array<{ id: string; version: number; state: string; assigned_to?: string }> }>)
  const persisted = async (state: string, version: number) => { await expect.poll(async () => { const body = await findingAPI(); return body.items[0] }).toMatchObject({ state, version }); return (await findingAPI()).items[0] }
  let current = (await findingAPI()).items[0]
  expect(current?.state).toBe('open')
  await details.getByRole('button', { name: 'Assign to me' }).click()
  current = await persisted('open', current.version + 1)
  expect(current.assigned_to).toBeTruthy()
  await expect(details.getByRole('button', { name: 'Unassign', exact: true })).toBeEnabled()
  await details.getByRole('button', { name: 'Unassign', exact: true }).click()
  current = await persisted('open', current.version + 1)
  expect(current.assigned_to ?? '').toBe('')
  await page.waitForTimeout(600)
  await details.getByLabel('Action reason').fill('Confirmed during triage')
  await details.getByRole('button', { name: 'Dismiss' }).click()
  current = await persisted('dismissed', current.version + 1)
  await page.waitForTimeout(600)
  await details.getByLabel('Action reason').fill('Reopening for follow-up')
  await details.getByRole('button', { name: 'Reopen' }).click()
  current = await persisted('open', current.version + 1)
  await page.waitForTimeout(600)
  await details.getByLabel('Action reason').fill('Awaiting upstream release')
  await details.getByRole('button', { name: 'Snooze 7 days' }).click()
  current = await persisted('snoozed', current.version + 1)
  expect(current.version).toBeGreaterThan(4)
})
