worker_processes 1;
error_log /dev/stderr notice;
pid /tmp/nginx/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;
  keepalive_timeout 65;
  client_body_temp_path /tmp/nginx/client_body;
  proxy_temp_path /tmp/nginx/proxy;
  fastcgi_temp_path /tmp/nginx/fastcgi;
  uwsgi_temp_path /tmp/nginx/uwsgi;
  scgi_temp_path /tmp/nginx/scgi;
  include /etc/nginx/conf.d/*.conf;

  server {
    listen 8080;
    server_name _;
    root /tmp/docs-root;
    index index.html;
    absolute_redirect off;

    location = / {
      return 301 /docs/;
    }

    location = /versions.json {
      add_header Cache-Control "no-cache";
      try_files $uri =404;
    }

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
