import { useQuery } from '@tanstack/react-query'
import { apiRequest } from '../api/client'
import { discoveryAPI } from '../api/discovery'
import type { RepairRun } from '../api/runs'
import type { components } from '../api/schema'
import { StatePanel } from '../components/StatePanel'
import { Button } from '../components/Accessible'

type Policy = components['schemas']['ResolvedPolicy']
type BaselineResponse = { run: RepairRun | null }
const path = (orgID: string, suffix: string) => `/api/v1/orgs/${encodeURIComponent(orgID)}${suffix}`
const text = (value: unknown) => value instanceof Error ? value.message : 'The server returned an unknown error.'

export function RepositoryBaseline({ orgID, repositoryID }: { orgID: string; repositoryID: string }) {
  const baseline = useQuery({ queryKey: ['org', orgID, 'repository', repositoryID, 'repair-baseline'], queryFn: ({ signal }) => apiRequest<BaselineResponse>(path(orgID, `/repositories/${encodeURIComponent(repositoryID)}/repair-baseline`), { signal }), enabled: !!repositoryID })
  const policies = useQuery({ queryKey: ['org', orgID, 'policies', 'effective', repositoryID], queryFn: ({ signal }) => apiRequest<Policy>(path(orgID, `/policies/effective?repository_id=${encodeURIComponent(repositoryID)}`), { signal }), enabled: !!repositoryID })
  const findings = useQuery({ queryKey: ['org', orgID, 'findings', 'repository-baseline', repositoryID], queryFn: ({ signal }) => discoveryAPI.findings(orgID, { repository_id: repositoryID, limit: 5, signal }), enabled: !!repositoryID })
  if (baseline.isLoading) return <StatePanel kind="loading" title="Loading repair baseline" detail="Fetching persisted repository evidence." />
  if (baseline.error) return <StatePanel kind="error" title="Repair baseline unavailable" detail={text(baseline.error)} action={<Button onClick={() => void baseline.refetch()}>Retry</Button>} />
  const run = baseline.data?.run
  return <section className="stack" aria-label="Repository repair baseline"><div className="subsection-actions"><h2>Observed execution evidence</h2><a className="button" href={`/org/${encodeURIComponent(orgID)}/runs${run?.task.id ? `?run=${encodeURIComponent(run.task.id)}` : ''}`}>{run ? 'Open run' : 'View runs'}</a></div>{run ? <RunEvidence run={run} /> : <div className="state-card"><h3>No recorded repair run</h3><p>Run a repair to record baseline evidence.</p></div>}<section className="detail-section"><h3>Effective policy</h3>{policies.isLoading ? <p className="table-meta">Loading policy evidence…</p> : policies.error ? <p className="error-text" role="alert">Policy evidence unavailable: {text(policies.error)}</p> : policies.data ? <dl className="detail-list"><div><dt>Hash</dt><dd><code>{policies.data.hash || 'Unknown'}</code></dd></div><div><dt>Paused</dt><dd>{policies.data.paused || policies.data.scope_paused ? 'Yes' : 'No'}</dd></div>{(policies.data.problems ?? []).length > 0 && <div><dt>Problems</dt><dd>{(policies.data.problems ?? []).join('; ')}</dd></div>}</dl> : <p>Policy evidence unavailable.</p>}</section><section className="detail-section"><h3>Current findings</h3><p><a href={`/org/${encodeURIComponent(orgID)}/findings?repository=${encodeURIComponent(repositoryID)}`}>View findings scoped to this repository</a></p>{findings.isLoading ? <p className="table-meta">Loading findings…</p> : findings.error ? <p className="error-text" role="alert">Findings unavailable: {text(findings.error)}</p> : findings.data?.items.length ? <ul className="compact-list">{findings.data.items.map(finding => <li key={finding.id}><a href={`/org/${encodeURIComponent(orgID)}/findings?repository=${encodeURIComponent(repositoryID)}&finding=${encodeURIComponent(finding.id)}`}>{finding.title}</a> · {finding.severity} · {finding.state}<ul><li>{(finding.evidence.checks ?? []).length} checks: {(finding.evidence.checks ?? []).slice(0, 5).map(check => check.name + ' (' + check.conclusion + ')').join(', ') || 'none recorded'}</li><li>{(finding.evidence.dependencies ?? []).length} dependencies: {(finding.evidence.dependencies ?? []).slice(0, 5).map(dependency => dependency.name + ' ' + dependency.from + ' → ' + dependency.to).join(', ') || 'none recorded'}</li></ul></li>)}</ul> : <p>No findings recorded for this repository.</p>}</section></section>
}

function RunEvidence({ run }: { run: RepairRun }) {
  const commands = run.context.plan?.recipe?.commands ?? []
  return <section className="detail-section"><h3>Frozen baseline</h3><dl className="detail-list"><div><dt>H baseline</dt><dd><code>{run.context.plan?.baseline_sha || 'Unknown'}</code></dd></div><div><dt>T target</dt><dd><code>{run.context.plan?.target_sha || 'Unknown'}</code></dd></div><div><dt>C native candidate</dt><dd><code>{run.candidate_sha || 'Unknown'}</code></dd></div><div><dt>Model</dt><dd>{run.task.model_route || run.context.model || 'Unknown'}</dd></div><div><dt>Runner pool</dt><dd>{run.task.runner_pool_id || 'Unknown'}</dd></div></dl><p className="table-meta">Recorded {new Date(run.updated_at).toLocaleString()} · Task state {run.task.state} · Report {run.report?.state || 'Unknown'}</p><h4>Frozen commands</h4>{commands.length ? <ul className="compact-list">{commands.map(command => <li key={command.id}><code>{command.id}: {command.args.join(' ')}</code> · {command.directory} · {command.timeout_seconds}s · {command.report_format}</li>)}</ul> : <p>Frozen commands unavailable.</p>}<p className="table-meta">Evidence is pinned to the recorded revisions. No current repository health is inferred.</p></section>
}
