import { type FormEvent, useEffect, useState } from 'react'
import { useInfiniteQuery, useQuery } from '@tanstack/react-query'
import { useSearch } from '@tanstack/react-router'
import { Button } from '../components/Accessible'
import { DataTable, EmptyTable } from '../components/DataTable'
import { StatePanel } from '../components/StatePanel'
import { StatusBadge } from '../components/Status'
import { useSession } from './query'
import { ReforgeAPIError } from '../api/client'
import { usageAPI, type Amount, type Caps, type Limit, type UsageFilters } from '../usage-api'

const errorText = (value: unknown) => value instanceof Error ? value.message : 'The server returned an unknown error.'
const money = (value: number) => `${(value / 1_000_000).toFixed(6)} USD (estimate)`
const amount = (value: Amount, quota = false) => `${value.tokens.toLocaleString()} tokens · ${value.requests} requests · ${value.milliseconds} ms${quota ? ' · subscription quota' : ` · ${money(value.micro_usd)}`}`
const dateTime = (value: string, end: boolean) => value ? new Date(Date.parse(`${value}T00:00:00Z`) + (end ? 86_400_000 : 0)).toISOString() : undefined
const emptyLimit = (kind: string, id: string): Limit => ({ scope: { kind, id }, period: 'daily', caps: {}, paused: false, version: 0, held: { micro_usd: 0, tokens: 0, milliseconds: 0, requests: 0, concurrency: 0 }, spent: { micro_usd: 0, tokens: 0, milliseconds: 0, requests: 0, concurrency: 0 } })

export function UsagePage({ orgID }: { orgID: string }) {
  const search = useSearch({ strict: false }) as Record<string, string | undefined>
  const requestedScope = typeof search.scope_kind === 'string' && typeof search.scope_id === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(search.scope_id) && ['organisation', 'team', 'repository', 'connection', 'campaign'].includes(search.scope_kind) ? { kind: search.scope_kind, id: search.scope_id } : undefined
  const session = useSession()
  const csrf = session.data?.csrf_token ?? ''
  const role = session.data?.memberships.find(item => item.org_id === orgID)?.role
  const canWrite = role === 'owner'
  const [draft, setDraft] = useState<UsageFilters>({ limit: 50 })
  const [filters, setFilters] = useState<UsageFilters>({ limit: 50 })
  const [scope, setScope] = useState(() => requestedScope ?? { kind: 'organisation', id: orgID })
  const [budget, setBudget] = useState<Limit>()
  const [saveError, setSaveError] = useState('')
  const [saving, setSaving] = useState(false)
  const [routeModel, setRouteModel] = useState('')
  const [routeName, setRouteName] = useState('default')
  const [routeInputs, setRouteInputs] = useState({ model: '', name: 'default' })
  const usage = useInfiniteQuery({ queryKey: ['org', orgID, 'usage', filters], queryFn: ({ pageParam, signal }) => usageAPI.list(orgID, { ...filters, cursor: pageParam, signal }), initialPageParam: undefined as string | undefined, getNextPageParam: page => page.complete ? undefined : page.next_cursor })
  const summary = useQuery({ queryKey: ['org', orgID, 'usage-summary', filters], queryFn: ({ signal }) => usageAPI.summary(orgID, { ...filters, signal }) })
  const budgetQuery = useQuery({ queryKey: ['org', orgID, 'budget', scope.kind, scope.id], queryFn: ({ signal }) => usageAPI.budget(orgID, scope.kind, scope.id, signal), enabled: !!scope.id })
  const route = useQuery({ queryKey: ['org', orgID, 'budget-route', filters.connection_id, routeInputs], queryFn: ({ signal }) => usageAPI.route(orgID, filters.connection_id!, routeInputs.model, routeInputs.name, signal), enabled: !!filters.connection_id && !!routeInputs.model && !!routeInputs.name })
  useEffect(() => { setBudget(undefined); setSaveError('') }, [scope.kind, scope.id])
  useEffect(() => { setScope(requestedScope ?? { kind: 'organisation', id: orgID }) }, [requestedScope?.kind, requestedScope?.id, orgID])
  const rows = usage.data?.pages.flatMap(page => page.items) ?? []
  const currentBudget = budget?.scope.kind === scope.kind && budget.scope.id === scope.id ? budget : budgetQuery.data
  const applyFilters = (event: FormEvent) => { event.preventDefault(); setFilters({ ...draft, since: dateTime(draft.since ?? '', false), until: dateTime(draft.until ?? '', true), cursor: undefined }); setRouteInputs({ model: routeModel.trim(), name: routeName.trim() || 'default' }) }
  const save = async () => { if (!currentBudget || saving) return; setSaving(true); setSaveError(''); try { await usageAPI.saveBudget(orgID, currentBudget, csrf); setBudget(undefined); await budgetQuery.refetch() } catch (reason) { setSaveError(errorText(reason)) } finally { setSaving(false) } }
  const scopeChanged = (kind: string) => setScope({ kind, id: kind === 'organisation' ? orgID : '' })
  const createBudget = () => { if (scope.id) setBudget(emptyLimit(scope.kind, scope.id)) }
  return <div className="stack usage-page">
    <section className="state-card" aria-label="Usage filters"><form className="form-grid" aria-label="Usage filters" onSubmit={applyFilters}>
      <label>Repository ID<input value={draft.repository_id ?? ''} onChange={event => setDraft({ ...draft, repository_id: event.target.value || undefined })} /></label><label>Team ID<input value={draft.team_id ?? ''} onChange={event => setDraft({ ...draft, team_id: event.target.value || undefined })} /></label><label>Recipe<input value={draft.recipe ?? ''} onChange={event => setDraft({ ...draft, recipe: event.target.value || undefined })} /></label><label>Provider<input value={draft.provider ?? ''} onChange={event => setDraft({ ...draft, provider: event.target.value || undefined })} /></label><label>Connection ID<input value={draft.connection_id ?? ''} onChange={event => setDraft({ ...draft, connection_id: event.target.value || undefined })} /></label><label>State<select value={draft.state ?? ''} onChange={event => setDraft({ ...draft, state: event.target.value || undefined })}><option value="">All states</option><option value="reserved">Reserved</option><option value="dispatched">Dispatched</option><option value="settled">Settled</option><option value="unknown">Unknown</option><option value="cancelled">Cancelled</option></select></label><label>Since (UTC)<input type="date" value={(draft.since ?? '').slice(0, 10)} onChange={event => setDraft({ ...draft, since: event.target.value })} /></label><label>Until (UTC, inclusive)<input type="date" value={(draft.until ?? '').slice(0, 10)} onChange={event => setDraft({ ...draft, until: event.target.value })} /></label><label>Billing model<input value={routeModel} onChange={event => setRouteModel(event.target.value)} /></label><label>Route name<input value={routeName} onChange={event => setRouteName(event.target.value)} /></label><div><Button className="button button-primary" type="submit">Apply filters</Button></div>
    </form>{(usage.isLoading || summary.isLoading) && <p role="status">Loading usage…</p>}{(usage.error || summary.error) && <StatePanel kind="error" title="Usage unavailable" detail={errorText(usage.error ?? summary.error)} action={<Button onClick={() => { void usage.refetch(); void summary.refetch() }}>Retry</Button>} />}{summary.data && <dl className="detail-list"><div><dt>API cost estimate (not invoice)</dt><dd>{money(summary.data.estimated_cost_micro_usd)}</dd></div><div><dt>Recorded tokens</dt><dd>{summary.data.known_tokens.toLocaleString()}</dd></div><div><dt>Unknown usage maximum</dt><dd>{amount(summary.data.unknown_maximum)}</dd></div><div><dt>Reserved and held</dt><dd>{amount(summary.data.held)}</dd></div></dl>}</section>
    <section className="state-card" aria-label="Budget">{!canWrite && <p>Budget changes require organisation owner access.</p>}<div className="row-actions"><label>Scope<select value={scope.kind} onChange={event => scopeChanged(event.target.value)}><option value="organisation">Organisation</option><option value="team">Team</option><option value="repository">Repository</option><option value="connection">Connection</option><option value="campaign">Campaign</option></select></label><label>Scope ID<input value={scope.id} onChange={event => setScope({ ...scope, id: event.target.value })} /></label></div>{budgetQuery.error && <p className="error-text" role="alert">Budget unavailable: {errorText(budgetQuery.error)}</p>}{!currentBudget && scope.id && budgetQuery.error instanceof ReforgeAPIError && budgetQuery.error.code === 'budget_unconfigured' && <Button disabled={!canWrite || saving} onClick={createBudget}>Create budget</Button>}{currentBudget && <BudgetEditor limit={currentBudget} editable={canWrite && !saving} csrf={csrf} saving={saving} onChange={setBudget} onSave={save} error={saveError} />}{route.error && <p className="error-text" role="alert">Route unavailable: {errorText(route.error)}</p>}{route.data && <p className="table-meta">Route {route.data.name}: {route.data.model} · pricing {route.data.pricing_version} · {route.data.qualified ? 'qualified by backend' : 'not qualified'} · {route.data.mode === 'quota' ? 'Subscription quota; no automatic paid fallback' : 'Priced API usage'}.</p>}</section>
    <section className="state-card" aria-label="Usage records"><DataTable caption="Usage records"><table><thead><tr><th>Repository</th><th>Provider / recipe</th><th>State</th><th>Usage</th></tr></thead><tbody>{rows.map(row => <tr key={row.reservation.id}><td>{row.repository_name}</td><td>{row.provider} · {row.recipe}</td><td><StatusBadge label={row.reservation.state} tone={row.reservation.state === 'unknown' ? 'amber' : 'green'} /></td><td>{row.reservation.actual ? amount(row.reservation.actual, row.reservation.route.mode === 'quota') : row.reservation.state === 'cancelled' ? 'Cancelled; hold released' : `Held maximum ${amount(row.reservation.maximum, row.reservation.route.mode === 'quota')}`}</td></tr>)}</tbody></table>{!rows.length && <EmptyTable label="No usage records match these filters." />}</DataTable>{usage.hasNextPage && <Button disabled={usage.isFetchingNextPage} onClick={() => void usage.fetchNextPage()}>{usage.isFetchingNextPage ? 'Loading…' : 'Load more usage'}</Button>}</section>
  </div>
}

function BudgetEditor({ limit, editable, csrf, saving, onChange, onSave, error }: { limit: Limit; editable: boolean; csrf: string; saving: boolean; onChange: (limit: Limit) => void; onSave: () => void; error: string }) {
  const cap = (key: keyof Caps, value: string) => onChange({ ...limit, caps: { ...limit.caps, [key]: value === '' ? undefined : Number(value) } })
  const localDate = (value?: string) => value?.slice(0, 16) ?? ''
  const setDate = (key: 'start' | 'end', value: string) => onChange({ ...limit, [key]: value ? `${value}:00Z` : undefined })
  return <div className="stack"><div className="form-grid"><label>Period<select disabled={!editable || limit.version > 0} value={limit.period} onChange={event => onChange({ ...limit, period: event.target.value, start: undefined, end: undefined })}><option value="daily">Daily</option><option value="monthly">Monthly</option><option value="custom">Custom</option></select></label>{limit.period === 'custom' && <><label>Start (UTC)<input type="datetime-local" disabled={!editable || limit.version > 0} value={localDate(limit.start)} onChange={event => setDate('start', event.target.value)} /></label><label>End (UTC)<input type="datetime-local" disabled={!editable || limit.version > 0} value={localDate(limit.end)} onChange={event => setDate('end', event.target.value)} /></label></>}{(['micro_usd', 'tokens', 'milliseconds', 'requests', 'concurrency'] as const).map(key => <label key={key}>{key}<input type="number" min="0" step="1" disabled={!editable} value={limit.caps[key] ?? ''} onChange={event => cap(key, event.target.value)} /></label>)}<label className="checkbox-label"><input type="checkbox" disabled={!editable} checked={limit.paused} onChange={event => onChange({ ...limit, paused: event.target.checked })} /> Paused</label></div><p className="table-meta">Version {limit.version} · held {amount(limit.held)} · settled {amount(limit.spent)}.</p>{error && <p className="error-text" role="alert">{error}</p>}<Button className="button button-primary" disabled={!editable || !csrf || saving} onClick={onSave}>{saving ? 'Saving…' : 'Save budget'}</Button></div>
}
