import { apiRequest } from './api/client'

export type Qualification = { provider: string; server_version: string; connection_version: number; evidence_reference: string; evidence_sha256: string; verified_at: string; expires_at: string; pinned_inputs: boolean; native_enforcement: boolean; environment_serialization: boolean; no_bypass: boolean }
export type Workflow = { id: string; path: string; ref: string; sha: string; config_sha256: string; inputs: Record<string, string> }
export type Configuration = { native_environment?: string; environment: string; repository_id: string; version: number; enabled: boolean; mode: string; workflow: Workflow; recovery_workflow?: Workflow; provenance_public_key: string; health_public_key: string; health_checks: string[]; observation_seconds: number; max_evidence_age_seconds: number; deadline_seconds: number; qualification: Qualification }
export type PreviewRequest = { change_id: string; source_sha: string; artifact_digest: string; provenance: { document: { org_id: string; repository_id: string; source_sha: string; artifact_digest: string; build_id: string; issued_at: string; expires_at: string }; signature: string }; recovery_of?: string; restore_deployment_id?: string }
export type TrackRequest = PreviewRequest & { run_id: string; idempotency_key: string }
export type Gate = { id: string; environment: string; repository_id: string; connection_id: string; connection_version: number; configuration_version: number; request: PreviewRequest; pipeline: { workflow_sha: string; rules_hash: string; repository: Record<string, unknown>; workflow_id: string; workflow_path: string; config_sha256: string; ref: string; source_sha: string; artifact_digest: string; environment: string; correlation_id: string; inputs: Record<string, string>; observe_only: boolean; run_id: string; requested_at: string }; native: { state: string; native_enforced: string; blockers: string[]; approval_url: string; environment: string; rules_hash: string }; binding: { [key: string]: unknown }; decision: { outcome: string; blockers?: string[]; required_actions?: string[] }; blockers: string[]; expires_at: string }
export type HealthReport = { org_id: string; deployment_id: string; environment: string; configuration_version: number; source_sha: string; artifact_digest: string; run_id: string; run_attempt: number; revision: string; healthy: boolean; checks: Record<string, boolean>; observed_at: string; nonce: string }
export type Operation = { cancel_requested: boolean; cancel_state: string; id: string; environment: string; repository_id: string; gate_id: string; state: string; reason: string; version: number; requested_by: string; finished_at?: string | null; native?: { workflow_sha: string; created_at: string; id: string; state: string; source_sha: string; artifact_digest: string; environment: string; correlation_id: string; workflow_id: string; workflow_path: string; ref: string; event: string; run_attempt: number; url: string; health: string; observed_at: string; updated_at: string }; recovery_of?: string; created_at: string; updated_at: string }
export type OperationPage = { items: Operation[]; next_cursor?: string; complete: boolean }
export type DeploymentDetail = { operation: Operation; gate?: Gate; health?: HealthReport }
const path = (orgID: string, suffix: string) => `/api/v1/orgs/${encodeURIComponent(orgID)}${suffix}`
export const deploymentAPI = {
  configurations: (orgID: string, signal?: AbortSignal) => apiRequest<{ items: Configuration[] }>(path(orgID, '/deployment-configurations'), { signal }),
  deployments: (orgID: string, params: { repositoryID?: string; environment?: string; cursor?: string; signal?: AbortSignal } = {}) => { const query = new URLSearchParams({ limit: '50' }); if (params.repositoryID) query.set('repository_id', params.repositoryID); if (params.environment) query.set('environment', params.environment); if (params.cursor) query.set('cursor', params.cursor); return apiRequest<OperationPage>(path(orgID, `/deployments?${query}`), { signal: params.signal }) },
  deployment: (orgID: string, deploymentID: string, signal?: AbortSignal) => apiRequest<DeploymentDetail>(path(orgID, `/deployments/${encodeURIComponent(deploymentID)}`), { signal }),
  preview: (orgID: string, environment: string, request: PreviewRequest, csrf: string) => apiRequest<Gate>(path(orgID, `/deployment-configurations/${encodeURIComponent(environment)}/preview`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request) }, csrf),
  request: (orgID: string, gateID: string, idempotencyKey: string, csrf: string) => apiRequest<Operation>(path(orgID, '/deployments'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ gate_id: gateID, idempotency_key: idempotencyKey }) }, csrf),
  track: (orgID: string, environment: string, request: TrackRequest, csrf: string) => apiRequest<Operation>(path(orgID, `/deployment-configurations/${encodeURIComponent(environment)}/track`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request) }, csrf),
  cancel: (orgID: string, deploymentID: string, version:number, csrf:string)=>apiRequest<Operation>(path(orgID,`/deployments/${encodeURIComponent(deploymentID)}/cancel`),{method:'POST',headers:{'If-Match':`"${version}"`}},csrf),
  observe: (orgID: string, deploymentID: string, csrf: string) => apiRequest<Operation>(path(orgID, `/deployments/${encodeURIComponent(deploymentID)}/observe`), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }, csrf),
}
